# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pagina.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(985, 564)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(470, 340, 75, 23))
        self.pushButton.setObjectName("pushButton")


        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 340, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")


        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 420, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")


        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(210, 30, 481, 192))
        self.tableView.setObjectName("tableView")


        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(290, 250, 291, 20))
        self.lineEdit.setObjectName("lineEdit")


        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 290, 291, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")


        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(380, 390, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.label_nome = QtWidgets.QLabel(Dialog)
        self.label_nome.setGeometry(QtCore.QRect(210, 250, 60, 20))
        self.label_nome.setText("Nome:")
        
        self.label_email = QtWidgets.QLabel(Dialog)
        self.label_email.setGeometry(QtCore.QRect(210, 290, 60, 20))
        self.label_email.setText("Email:")
        
        self.label_id = QtWidgets.QLabel(Dialog)
        self.label_id.setGeometry(QtCore.QRect(210, 390, 60, 20))
        self.label_id.setText("ID:")


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "adicionar"))
        self.pushButton_2.setText(_translate("Dialog", "atualizar"))
        self.pushButton_3.setText(_translate("Dialog", "deletar"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
